version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ldore
      POSTGRES_PASSWORD: 7d8jwl59
      POSTGRES_DB: lenslocked
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 3333:8080
    environment:
      ADMINER_DESIGN: dracula
